### ISSUE TITLE
KeyError while launching

### ISSUE THREAD

**Issue by santoshbmath** [raunit-x/WazirX-Portfolio-Tracker#1]
Hi,

I am getting following error while running the tracker. I am using python 3.9.2 on Windows.

Traceback (most recent call last):
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 207, in <module>
    main()
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 199, in main
    token_info = get_token_info(payloads, trading_report)
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 57, in get_token_info
    token_info = {
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 59, in <dictcomp>
    TYPE: payloads[ticker].get(),
KeyError: 'WRX'

Thanks,
Santosh

**Comment by raunit-x** [comment]
Hi Santosh,
My apologies! It would be great if you could share your `trading_report.xlsx` file. Currently, it doesn't support `WRX` as a currency (it can be treated as a holding, of course). So if you are using WRX as an exchange token, this error might come up!

**Comment by santoshbmath** [comment]
I deleted rows related to WRX, now i am getting error for next one,

{'SHIB': 500000.0, 'HBAR': 50.0, 'COS': 400.0, 'SRM': 4.0, 'VET': 300.0, 'BAT': 30.0, 'XRP': 25.0, 'BTT': 22500.0, 'DOGE': 200.0, 'ALGO': 20.0, 'BAL': 2.0, 'WIN': 16400.0, 'DOCK': 150.0, 'ADA': 125.0, 'NFT': 10537.454397, 'REEF': 1000.0, 'STPT': 100.0, 'TRX': 100.0, 'VIB': 100.0, 'LINK': 1.5, 'DOT': 1.5, 'COMP': 0.06, 'BNB': 0.03829776, 'ETH': 0.03501135, 'BTC': 0.00400001}
Traceback (most recent call last):
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 207, in <module>
    main()
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 199, in main
    token_info = get_token_info(payloads, trading_report)
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 57, in get_token_info
    token_info = {
  File "C:\Users\maths\Desktop\WazirX-Portfolio-Tracker-main\main.py", line 59, in <dictcomp>
    TOTAL_VALUE: Decimal(payloads[ticker][TYPE]) * Decimal(num_coins),
KeyError: 'SHIB'

**Comment by raunit-x** [comment]
Have you pulled from the latest commits? Otherwise, feel free to share the trading report and I would debug it in no time.

**Comment by santoshbmath** [comment]
Share your emails address, i will share the trading report.

**Comment by santoshbmath** [comment]
Also, i am not sure from which sheet from trading report its picking WRX. I deleted WRX records from everywhere.

By any chance is it caches data/payload anywhere?

**Comment by raunit-x** [comment]
Yes, it caches last payload in a new directory called `Previous Prices`. Share the report - raunit88@gmail.com

**Comment by santoshbmath** [comment]
Sent you my trade report for analysis.

**Comment by raunit-x** [comment]
Ok, I got the error. First, pull the latest commit then remove the `NFT` from your account balances sheet. Then you will be good to go. Don't forget to repopulate the deposits and withdrawals sheet otherwise you will get a division by zero error :)

**Comment by Anurag5086** [comment]
Hey @raunit-x , im facing this error - 
Traceback (most recent call last):RYING THE SERVERS IN: 00 SECONDS
  File "C:\Users\Ayush PC\Desktop\WazirX-Portfolio-Tracker\main.py", line 205, in <module>        
    main()
  File "C:\Users\Ayush PC\Desktop\WazirX-Portfolio-Tracker\main.py", line 196, in main
    payloads = load_from_pickle()
  File "C:\Users\Ayush PC\Desktop\WazirX-Portfolio-Tracker\utils.py", line 14, in load_from_pickle
    return pickle.load(f)
TypeError: a bytes-like object is required, not 'str'

**Comment by Anurag5086** [comment]
How can we add more coins? There are very limited coins.

**Comment by raunit-x** [comment]
Hi Anurag,
Please check if the variable `f` is a File Object instead of just a file path.
Also, you can add support for more coins as a medium of exchange from the `currecncy` variable. Let me see what I can do make it more modular so that other people can add support for more coins.
